# Generated by Django 3.0.8 on 2020-09-16 01:24

from django.conf import settings
from django.db import migrations, models
from django.utils.translation import ugettext_lazy as _


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Action',
            name='actor',
            field=models.ForeignKey(
                settings.AUTH_USER_MODEL, verbose_name=_('Actor'),
                related_name='workflow_actions', null=True,
            ),
        ),
    ]
